controller:
  componentName: "jenkins-controller"
  adminSecretKey: "jenkins-admin-password"
  serviceType: "LoadBalancer"
  installPlugins:
    - "kubernetes:4251.v130c197fa_043"
    - "workflow-aggregator:596.v8c21c963d92d"
    - "git:5.2.1"
    - "pipeline-stage-view:2.34"
    - "configuration-as-code:1775.v810d70a_730cf"
    - "credentials-binding:687.v619cb_15e923f"

  JCasC:
    enabled: true
    configScripts:
      cloud-config: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                templates:
                  - name: "kaniko-agent"
                    label: "kaniko-git"
                    serviceAccount: "jenkins"
                    containers:
                      - name: "kaniko"
                        image: "gcr.io/kaniko-project/executor:v1.14.0-debug"
                        command: "/busybox/cat"
                        ttyEnabled: true
                      - name: "git-tools"
                        image: "alpine/git:2.43.0"
                        command: "/bin/sh"
                        args: "-c cat"
                        ttyEnabled: true

agent:
  enabled: false