apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secret.secretKey | required "secret.secretKey is required" | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | required "secret.postgresPassword is required" | quote }}